# -*- coding: utf-8 -*-
"""streamlit_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16_E1VS9B34BjyMmycIV1dE6qZYzHCcyd
"""

import streamlit as st
import torch
import torch.nn as nn
import torch.nn.functional as F
import librosa
import numpy as np
import tempfile

from torchvision.models import efficientnet_b0

# -----------------------------
# Load Model
# -----------------------------
@st.cache_resource
def load_model():

    device = torch.device("cpu")

    model = efficientnet_b0(weights=None)
    model.classifier[1] = nn.Linear(
        model.classifier[1].in_features,
        2
    )

    model.load_state_dict(
        torch.load(
            "outputs/best_model_v2.pth",
            map_location=device
        )
    )

    model.eval()

    return model, device


model, device = load_model()

# -----------------------------
# Audio Preprocessing
# -----------------------------
def preprocess_audio(file_path):

    y, sr = librosa.load(
        file_path,
        sr=16000,
        mono=True
    )

    mel = librosa.feature.melspectrogram(
        y=y,
        sr=sr,
        n_mels=128
    )

    mel_db = librosa.power_to_db(
        mel,
        ref=np.max
    )

    mel_db = (
        mel_db - mel_db.min()
    ) / (
        mel_db.max() - mel_db.min() + 1e-8
    )

    mel_tensor = torch.tensor(
        mel_db,
        dtype=torch.float32
    ).unsqueeze(0).unsqueeze(0)

    mel_tensor = F.interpolate(
        mel_tensor,
        size=(224, 224),
        mode="bilinear",
        align_corners=False
    )

    mel_tensor = mel_tensor.repeat(
        1, 3, 1, 1
    )

    return mel_tensor


# -----------------------------
# Prediction
# -----------------------------
def predict(file_path):

    x = preprocess_audio(file_path)

    with torch.no_grad():

        output = model(x)

        probs = F.softmax(
            output,
            dim=1
        )

        pred = torch.argmax(
            probs,
            dim=1
        ).item()

        confidence = torch.max(
            probs
        ).item()

    label = (
        "Deepfake (AI Generated)"
        if pred == 0
        else "Genuine (Human)"
    )

    return label, confidence


# -----------------------------
# Streamlit UI
# -----------------------------
st.set_page_config(
    page_title="Deepfake Audio Detector",
    page_icon=""
)

st.title("Deepfake Audio Detection")

st.write(
    "Upload an audio file and determine "
    "whether it is Human or AI Generated."
)

uploaded_file = st.file_uploader(
    "Upload Audio",
    type=["wav", "mp3", "ogg"]
)

if uploaded_file is not None:

    st.audio(uploaded_file)

    with tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".wav"
    ) as tmp_file:

        tmp_file.write(
            uploaded_file.read()
        )

        temp_path = tmp_file.name

    if st.button("Analyze Audio"):

        with st.spinner(
            "Analyzing..."
        ):

            label, confidence = predict(
                temp_path
            )

        st.success(
            f"Prediction: {label}"
        )

        st.metric(
            "Confidence",
            f"{confidence*100:.2f}%"
        )

